<?php
echo "GRUPO 3";
echo "REDES DE COMPUTADORES - ESTÁCIO DE SA - FUNDAMENTOS DE SI ";
echo "DANIEL VICTOR";
echo "DOUGLAS HENRIQUE";
echo "FABIANO RODRIGUES";
echo "GLAUCO LUIZ";
echo "MARCELO FELIPE";
echo "E NOIS!";
?>
